name: Windows CI

on:
  # push:
  #   branches:
  #     - dev/bare
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        #architecture: [x86, x64, ARM64]
        #configuration: [Debug, Release]
        architecture: [x64]
        configuration: [Debug]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 16

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 16.8

    - name: Check node modules cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install node modules
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --pure-lockfile

    # - name: Decode PFX
    #   run: |
    #     $PfxBytes = [System.Convert]::FromBase64String("${{ secrets.PFX }}")
    #     $PfxPath = [System.IO.Path]::GetFullPath( (Join-Path -Path ProjectDirectoryPath -ChildPath GitHubActionsWorkflow.pfx) )
    #     [System.IO.File]::WriteAllBytes("$PfxPath", $PfxBytes)

    - name: Build
      run: yarn react-native run-windows --logging --no-packager --no-launch --no-deploy --arch ${{ matrix.architecture }} ${{ matrix.configuration == 'Release' && '--release' || '' }} --msbuildprops PackageCertificateKeyFile=${{ github.workspace }}\windows\spacebar\spacebar_TemporaryKey.pfx

    # - name: Remove PFX
    #   run: |
    #     $certificatePath = Join-Path -Path ProjectDirectoryPath -ChildPath GitHubActionsWorkflow.pfx
    #     Write-Host $certificatePath
    #     Remove-Item -path $certificatePath